spring.application.name=LabVIRT

server.port=${SERVER_PORT:8080}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/labvirt}
spring.datasource.username=${DATABASE_USERNAME:labvirt}
spring.datasource.password=${DATABASE_PASSWORD:labvirt}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
